[package]
name = "knot"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
bytemuck = { version = "1", features = ["derive"] }
cosmic-text = "0.19"
pollster = "0.4"
sysinfo = "0.32"
wgpu = "29"
winit = "0.30"

[lib]
name = "knot"
path = "src/lib.rs"

[[bin]]
name = "knot"
path = "src/main.rs"

[[bin]]
name = "bench"
path = "src/bin/bench.rs"
